//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Drawing;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Captain.Application {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    public class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("Captain.Application.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution type.
        /// </summary>
        public static string AboutWindow_DistributionType {
            get {
                return ResourceManager.GetString("AboutWindow_DistributionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        public static string AboutWindow_DistType_Full {
            get {
                return ResourceManager.GetString("AboutWindow_DistType_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standalone.
        /// </summary>
        public static string AboutWindow_DistType_Standalone {
            get {
                return ResourceManager.GetString("AboutWindow_DistType_Standalone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying updates.
        /// </summary>
        public static string AboutWindow_UpdateStatusApplying {
            get {
                return ResourceManager.GetString("AboutWindow_UpdateStatusApplying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates.
        /// </summary>
        public static string AboutWindow_UpdateStatusChecking {
            get {
                return ResourceManager.GetString("AboutWindow_UpdateStatusChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading updates.
        /// </summary>
        public static string AboutWindow_UpdateStatusDownloading {
            get {
                return ResourceManager.GetString("AboutWindow_UpdateStatusDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart {0} to complete the update.
        /// </summary>
        public static string AboutWindow_UpdateStatusReadyToRestart {
            get {
                return ResourceManager.GetString("AboutWindow_UpdateStatusReadyToRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://git.io/captain.
        /// </summary>
        public static string AboutWindow_URI {
            get {
                return ResourceManager.GetString("AboutWindow_URI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap AcrylicNoiseTexture {
            get {
                object obj = ResourceManager.GetObject("AcrylicNoiseTexture", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy URI.
        /// </summary>
        public static string ActionControl_ContextMenu_CopyUri {
            get {
                return ResourceManager.GetString("ActionControl_ContextMenu_CopyUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open.
        /// </summary>
        public static string ActionControl_ContextMenu_Open {
            get {
                return ResourceManager.GetString("ActionControl_ContextMenu_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in &amp;folder….
        /// </summary>
        public static string ActionControl_ContextMenu_OpenInFolder {
            get {
                return ResourceManager.GetString("ActionControl_ContextMenu_OpenInFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error ocurred while performing this action..
        /// </summary>
        public static string ActionControl_ErrorDetailsDefaultContent {
            get {
                return ResourceManager.GetString("ActionControl_ErrorDetailsDefaultContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some tasks failed.
        /// </summary>
        public static string ActionErrorDialog_PartialFailureCaption {
            get {
                return ResourceManager.GetString("ActionErrorDialog_PartialFailureCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all output streams could process your capture. Refer to the application log for technical information..
        /// </summary>
        public static string ActionErrorDialog_PartialFailureContent {
            get {
                return ResourceManager.GetString("ActionErrorDialog_PartialFailureContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Action ({0}).
        /// </summary>
        public static string ActionPropertiesDialog_DefaultActionName {
            get {
                return ResourceManager.GetString("ActionPropertiesDialog_DefaultActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All actions failed.
        /// </summary>
        public static string ActionStatus_Tidbit_AllFailed {
            get {
                return ResourceManager.GetString("ActionStatus_Tidbit_AllFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording saved.
        /// </summary>
        public static string ActionStatus_Tidbit_AllSucceeded_Recording {
            get {
                return ResourceManager.GetString("ActionStatus_Tidbit_AllSucceeded_Recording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot taken.
        /// </summary>
        public static string ActionStatus_Tidbit_AllSucceeded_Screenshot {
            get {
                return ResourceManager.GetString("ActionStatus_Tidbit_AllSucceeded_Screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done – Some actions failed.
        /// </summary>
        public static string ActionStatus_Tidbit_SomeFailed {
            get {
                return ResourceManager.GetString("ActionStatus_Tidbit_SomeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap AeroIndicatorStrip {
            get {
                object obj = ResourceManager.GetObject("AeroIndicatorStrip", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static Icon AppIcon {
            get {
                object obj = ResourceManager.GetObject("AppIcon", resourceCulture);
                return ((Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About….
        /// </summary>
        public static string AppMenu_About {
            get {
                return ResourceManager.GetString("AppMenu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Exit.
        /// </summary>
        public static string AppMenu_Exit {
            get {
                return ResourceManager.GetString("AppMenu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Options….
        /// </summary>
        public static string AppMenu_Options {
            get {
                return ResourceManager.GetString("AppMenu_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap CapturePreviewUnavailable {
            get {
                object obj = ResourceManager.GetObject("CapturePreviewUnavailable", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap CaptureResultErrorDetails {
            get {
                object obj = ResourceManager.GetObject("CaptureResultErrorDetails", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap CaptureResultUri {
            get {
                object obj = ResourceManager.GetObject("CaptureResultUri", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static Icon ClipboardHandlerExtensionIcon {
            get {
                object obj = ResourceManager.GetObject("ClipboardHandlerExtensionIcon", resourceCulture);
                return ((Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap ClipperCorners {
            get {
                object obj = ResourceManager.GetObject("ClipperCorners", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap ClipperPickRegion {
            get {
                object obj = ResourceManager.GetObject("ClipperPickRegion", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap ClipperPickWindow {
            get {
                object obj = ResourceManager.GetObject("ClipperPickWindow", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        public static string CommonVariable_Day {
            get {
                return ResourceManager.GetString("CommonVariable_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to extension.
        /// </summary>
        public static string CommonVariable_Extension {
            get {
                return ResourceManager.GetString("CommonVariable_Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user folder.
        /// </summary>
        public static string CommonVariable_HomeDirectory {
            get {
                return ResourceManager.GetString("CommonVariable_HomeDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        public static string CommonVariable_Hour {
            get {
                return ResourceManager.GetString("CommonVariable_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute.
        /// </summary>
        public static string CommonVariable_Minute {
            get {
                return ResourceManager.GetString("CommonVariable_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month.
        /// </summary>
        public static string CommonVariable_Month {
            get {
                return ResourceManager.GetString("CommonVariable_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pictures folder.
        /// </summary>
        public static string CommonVariable_PicturesDirectory {
            get {
                return ResourceManager.GetString("CommonVariable_PicturesDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second.
        /// </summary>
        public static string CommonVariable_Second {
            get {
                return ResourceManager.GetString("CommonVariable_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to two-digit year.
        /// </summary>
        public static string CommonVariable_ShortYear {
            get {
                return ResourceManager.GetString("CommonVariable_ShortYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type.
        /// </summary>
        public static string CommonVariable_Type {
            get {
                return ResourceManager.GetString("CommonVariable_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year.
        /// </summary>
        public static string CommonVariable_Year {
            get {
                return ResourceManager.GetString("CommonVariable_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap CopyToClipboard {
            get {
                object obj = ResourceManager.GetObject("CopyToClipboard", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap EncoderOptions {
            get {
                object obj = ResourceManager.GetObject("EncoderOptions", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap EraseField {
            get {
                object obj = ResourceManager.GetObject("EraseField", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static Icon FileHandlerExtensionIcon {
            get {
                object obj = ResourceManager.GetObject("FileHandlerExtensionIcon", resourceCulture);
                return ((Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap FluentIndicatorStrip {
            get {
                object obj = ResourceManager.GetObject("FluentIndicatorStrip", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide error &amp;details.
        /// </summary>
        public static string GenericActionErrorDialog_HideDetails {
            get {
                return ResourceManager.GetString("GenericActionErrorDialog_HideDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show error &amp;details.
        /// </summary>
        public static string GenericActionErrorDialog_ShowDetails {
            get {
                return ResourceManager.GetString("GenericActionErrorDialog_ShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static Icon GenericExtensionIcon {
            get {
                object obj = ResourceManager.GetObject("GenericExtensionIcon", resourceCulture);
                return ((Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string HotkeyBox_ResetToolTipText {
            get {
                return ResourceManager.GetString("HotkeyBox_ResetToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag your mouse to select a screen region..
        /// </summary>
        public static string HUD_CropRectangleHint {
            get {
                return ResourceManager.GetString("HUD_CropRectangleHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save this recording?.
        /// </summary>
        public static string Hud_SnackBar_ClosePromptInstruction {
            get {
                return ResourceManager.GetString("Hud_SnackBar_ClosePromptInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] InvalidCursor {
            get {
                object obj = ResourceManager.GetObject("InvalidCursor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap NeutralResultOverlay {
            get {
                object obj = ResourceManager.GetObject("NeutralResultOverlay", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] NormalCursor {
            get {
                object obj = ResourceManager.GetObject("NormalCursor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring the application will delete all plugins, logs and customizations. We won&apos;t touch your captures..
        /// </summary>
        public static string OptionsWindow_RestoreDialogContent {
            get {
                return ResourceManager.GetString("OptionsWindow_RestoreDialogContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset everything.
        /// </summary>
        public static string OptionsWindow_RestoreDialogHardButton {
            get {
                return ResourceManager.GetString("OptionsWindow_RestoreDialogHardButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string OptionsWindow_RestoreDialogInstruction {
            get {
                return ResourceManager.GetString("OptionsWindow_RestoreDialogInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore options only.
        /// </summary>
        public static string OptionsWindow_RestoreDialogOptionsButton {
            get {
                return ResourceManager.GetString("OptionsWindow_RestoreDialogOptionsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced options.
        /// </summary>
        public static string OptionsWindow_Tasks_AdvancedOptions {
            get {
                return ResourceManager.GetString("OptionsWindow_Tasks_AdvancedOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic options.
        /// </summary>
        public static string OptionsWindow_Tasks_BasicOptions {
            get {
                return ResourceManager.GetString("OptionsWindow_Tasks_BasicOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These are not the droids you are looking for. Move along!.
        /// </summary>
        public static string OutputStreamSelectionDialog_EmptyMarkup {
            get {
                return ResourceManager.GetString("OutputStreamSelectionDialog_EmptyMarkup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Placeholder {
            get {
                object obj = ResourceManager.GetObject("Placeholder", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown publisher.
        /// </summary>
        public static string Plugin_DefaultPublisherName {
            get {
                return ResourceManager.GetString("Plugin_DefaultPublisherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Action.
        /// </summary>
        public static string PluginManager_DefaultActionName {
            get {
                return ResourceManager.GetString("PluginManager_DefaultActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration interface for this plugin cannot be displayed.
        ///Contact the plugin vendor for further information..
        /// </summary>
        public static string PluginManager_EncoderConfigurationUIError {
            get {
                return ResourceManager.GetString("PluginManager_EncoderConfigurationUIError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current monitor.
        /// </summary>
        public static string RegionType_ActiveMonitor {
            get {
                return ResourceManager.GetString("RegionType_ActiveMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active window.
        /// </summary>
        public static string RegionType_ActiveWindow {
            get {
                return ResourceManager.GetString("RegionType_ActiveWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed region.
        /// </summary>
        public static string RegionType_Fixed {
            get {
                return ResourceManager.GetString("RegionType_Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All monitors.
        /// </summary>
        public static string RegionType_FullDesktop {
            get {
                return ResourceManager.GetString("RegionType_FullDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string RegionType_Manual {
            get {
                return ResourceManager.GetString("RegionType_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap SaveToFile {
            get {
                object obj = ResourceManager.GetObject("SaveToFile", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {10}\Captures\{2}.{0}\{3}.{4}.{5}.{6}.{8}.
        /// </summary>
        public static string SaveToFile_DefaultNameTemplate {
            get {
                return ResourceManager.GetString("SaveToFile_DefaultNameTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to file.
        /// </summary>
        public static string SaveToFile_Name {
            get {
                return ResourceManager.GetString("SaveToFile_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap SnackBarClose {
            get {
                object obj = ResourceManager.GetObject("SnackBarClose", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap SnackBarGrip {
            get {
                object obj = ResourceManager.GetObject("SnackBarGrip", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap SnackBarMute {
            get {
                object obj = ResourceManager.GetObject("SnackBarMute", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap SnackBarOptions {
            get {
                object obj = ResourceManager.GetObject("SnackBarOptions", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap SnackBarPause {
            get {
                object obj = ResourceManager.GetObject("SnackBarPause", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap SnackBarRecord {
            get {
                object obj = ResourceManager.GetObject("SnackBarRecord", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap SnackBarResume {
            get {
                object obj = ResourceManager.GetObject("SnackBarResume", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap SnackBarScreenshot {
            get {
                object obj = ResourceManager.GetObject("SnackBarScreenshot", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap SnackBarStop {
            get {
                object obj = ResourceManager.GetObject("SnackBarStop", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap SnackBarUnmute {
            get {
                object obj = ResourceManager.GetObject("SnackBarUnmute", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap SuccessfulResultOverlay {
            get {
                object obj = ResourceManager.GetObject("SuccessfulResultOverlay", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We could not capture the screen due to an internal error.
        ///Tap here to see details..
        /// </summary>
        public static string Task_CaptureFailedBody {
            get {
                return ResourceManager.GetString("Task_CaptureFailedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture failed.
        /// </summary>
        public static string Task_CaptureFailedCaption {
            get {
                return ResourceManager.GetString("Task_CaptureFailedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required encoder may have not been properly initialized, there were no actions to take or an error occurred while trying to duplicate the desktop..
        /// </summary>
        public static string Task_CaptureFailedExtendedBody {
            get {
                return ResourceManager.GetString("Task_CaptureFailedExtendedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not capture the screen.
        /// </summary>
        public static string Task_CaptureFailedExtendedCaption {
            get {
                return ResourceManager.GetString("Task_CaptureFailedExtendedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record screen.
        /// </summary>
        public static string Task_DefaultRecordingTaskName {
            get {
                return ResourceManager.GetString("Task_DefaultRecordingTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take screenshot.
        /// </summary>
        public static string Task_DefaultScreenshotTaskName {
            get {
                return ResourceManager.GetString("Task_DefaultScreenshotTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all actions could process your capture..
        /// </summary>
        public static string Task_PartialSuccessBody {
            get {
                return ResourceManager.GetString("Task_PartialSuccessBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some actions failed.
        /// </summary>
        public static string Task_PartialSuccessCaption {
            get {
                return ResourceManager.GetString("Task_PartialSuccessCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All actions succeeded..
        /// </summary>
        public static string Task_SuccessBody {
            get {
                return ResourceManager.GetString("Task_SuccessBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot taken!.
        /// </summary>
        public static string Task_SuccessCaption {
            get {
                return ResourceManager.GetString("Task_SuccessCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View details.
        /// </summary>
        public static string Task_ViewDetailsAction {
            get {
                return ResourceManager.GetString("Task_ViewDetailsAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View failures.
        /// </summary>
        public static string Task_ViewFailuresAction {
            get {
                return ResourceManager.GetString("Task_ViewFailuresAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View results.
        /// </summary>
        public static string Task_ViewResultsAction {
            get {
                return ResourceManager.GetString("Task_ViewResultsAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap TaskAdd {
            get {
                object obj = ResourceManager.GetObject("TaskAdd", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap TaskDelete {
            get {
                object obj = ResourceManager.GetObject("TaskDelete", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Report….
        /// </summary>
        public static string TaskDialog_GenericReportButtonContent {
            get {
                return ResourceManager.GetString("TaskDialog_GenericReportButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap TaskEdit {
            get {
                object obj = ResourceManager.GetObject("TaskEdit", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The capture could not be processed..
        /// </summary>
        public static string TaskHelper_ActionFailedCaption {
            get {
                return ResourceManager.GetString("TaskHelper_ActionFailedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not initialize action..
        /// </summary>
        public static string TaskHelper_ActionInitializationFailedCaption {
            get {
                return ResourceManager.GetString("TaskHelper_ActionInitializationFailedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture failed.
        /// </summary>
        public static string TaskHelper_CaptureFailedCaption {
            get {
                return ResourceManager.GetString("TaskHelper_CaptureFailedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The video provider failed to capture your desktop..
        /// </summary>
        public static string TaskHelper_CaptureFailedContent {
            get {
                return ResourceManager.GetString("TaskHelper_CaptureFailedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Report….
        /// </summary>
        public static string TaskHelper_DisplayTaskExceptionDialog_ReportButtonCaption {
            get {
                return ResourceManager.GetString("TaskHelper_DisplayTaskExceptionDialog_ReportButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding failed.
        /// </summary>
        public static string TaskHelper_EncodingFailedCaption {
            get {
                return ResourceManager.GetString("TaskHelper_EncodingFailedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The encoder failed to process the captured image..
        /// </summary>
        public static string TaskHelper_EncodingFailedContent {
            get {
                return ResourceManager.GetString("TaskHelper_EncodingFailedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We could not initialize the image encoder..
        /// </summary>
        public static string TaskHelper_EncodingInitializationFailedContent {
            get {
                return ResourceManager.GetString("TaskHelper_EncodingInitializationFailedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such action loaded..
        /// </summary>
        public static string TaskHelper_NoSuchActionMessage {
            get {
                return ResourceManager.GetString("TaskHelper_NoSuchActionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This media is not supported by this action..
        /// </summary>
        public static string TaskHelper_UnsupportedMediaMessage {
            get {
                return ResourceManager.GetString("TaskHelper_UnsupportedMediaMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} actions.
        /// </summary>
        public static string TaskPropertiesDialog_MultipleActions {
            get {
                return ResourceManager.GetString("TaskPropertiesDialog_MultipleActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No actions.
        /// </summary>
        public static string TaskPropertiesDialog_NoActions {
            get {
                return ResourceManager.GetString("TaskPropertiesDialog_NoActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 action.
        /// </summary>
        public static string TaskPropertiesDialog_SingleAction {
            get {
                return ResourceManager.GetString("TaskPropertiesDialog_SingleAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap TaskRegionFixed {
            get {
                object obj = ResourceManager.GetObject("TaskRegionFixed", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap TaskRegionFullScreen {
            get {
                object obj = ResourceManager.GetObject("TaskRegionFullScreen", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap TaskRegionGrab {
            get {
                object obj = ResourceManager.GetObject("TaskRegionGrab", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap TaskTypeRecording {
            get {
                object obj = ResourceManager.GetObject("TaskTypeRecording", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap TaskTypeScreenshot {
            get {
                object obj = ResourceManager.GetObject("TaskTypeScreenshot", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording.
        /// </summary>
        public static string TemplateHelper_Type_Recording {
            get {
                return ResourceManager.GetString("TemplateHelper_Type_Recording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot.
        /// </summary>
        public static string TemplateHelper_Type_Screenshot {
            get {
                return ResourceManager.GetString("TemplateHelper_Type_Screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap TidbitError {
            get {
                object obj = ResourceManager.GetObject("TidbitError", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap TidbitInfo {
            get {
                object obj = ResourceManager.GetObject("TidbitInfo", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap TidbitOk {
            get {
                object obj = ResourceManager.GetObject("TidbitOk", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap TidbitWarning {
            get {
                object obj = ResourceManager.GetObject("TidbitWarning", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap UnsuccessfulResultOverlay {
            get {
                object obj = ResourceManager.GetObject("UnsuccessfulResultOverlay", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static Icon UpdateIcon {
            get {
                object obj = ResourceManager.GetObject("UpdateIcon", resourceCulture);
                return ((Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update {0}.
        /// </summary>
        public static string UpdaterUI_DialogCaption {
            get {
                return ResourceManager.GetString("UpdaterUI_DialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing update….
        /// </summary>
        public static string UpdaterUI_DialogInstallProgressText {
            get {
                return ResourceManager.GetString("UpdaterUI_DialogInstallProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading update….
        /// </summary>
        public static string UpdaterUI_DialogProgressText {
            get {
                return ResourceManager.GetString("UpdaterUI_DialogProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of {0} ({1}) is available—yours is {2}.
        ///Would you like to install it?.
        /// </summary>
        public static string UpdaterUI_DialogText {
            get {
                return ResourceManager.GetString("UpdaterUI_DialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Remind me later.
        /// </summary>
        public static string UpdaterUI_RemindLaterButton {
            get {
                return ResourceManager.GetString("UpdaterUI_RemindLaterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Update.
        /// </summary>
        public static string UpdaterUI_UpdateButton {
            get {
                return ResourceManager.GetString("UpdaterUI_UpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] WindowCursor {
            get {
                object obj = ResourceManager.GetObject("WindowCursor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to “{0}” properties – {01}.
        /// </summary>
        public static string WorkflowPropertyDialog_NamedWorkflowTitleFormat {
            get {
                return ResourceManager.GetString("WorkflowPropertyDialog_NamedWorkflowTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow properties – {0}.
        /// </summary>
        public static string WorkflowPropertyDialog_UnnamedWorkflowTitleFormat {
            get {
                return ResourceManager.GetString("WorkflowPropertyDialog_UnnamedWorkflowTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string WorkflowType_Motion {
            get {
                return ResourceManager.GetString("WorkflowType_Motion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Still image.
        /// </summary>
        public static string WorkflowType_Still {
            get {
                return ResourceManager.GetString("WorkflowType_Still", resourceCulture);
            }
        }
    }
}
